version: '3.9'
services:

  nginx:
    ports:
    - '8080:80'
    restart: always
    networks:
      - backend
    build:
      context: .
      dockerfile: nginx/Dockerfile

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - backend
    ports:
      - 5432:5432
    volumes:
     - pg-data:/var/lib/postgresql/data

  api-geteway:
    build:
     context: api-gateway
    depends_on:
      - database
    networks:
      - backend
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 200M   

networks:
  backend:

volumes:
  pg-data: