version: '3.9'
services:

  nginx:
    ports:
    - "80:80"
    - "443:443"
    restart: always
    networks:
      - backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - auth-gateway

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - backend
    ports:
      - "5432:5432"
    volumes:
     - pg-data:/var/lib/postgresql/data
    extra_hosts:
    - "host.docker.internal:host-gateway"

  auth-gateway:
    build:
     context: auth-gateway
    environment:
      "env": "prod"
    depends_on:
      - database
    networks:
      - backend
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 200M   
  
  auth:
    build:
     context: microservices/auth
    depends_on:
      - database
    networks:
      - backend
    environment:
      "env": "prod"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 200M   
  
  migration-service:
    build:
     context: microservices/migration-service
    environment:
      "env": "prod"
    depends_on:
      - database
    networks:
      - backend
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 200M   
  
  # register-service:
  #   build:
  #    context: microservices/register-service
  #   depends_on:
  #     - database
  #   networks:
  #     - backend
  #   deploy:
  #     replicas: 1
  #     resources:
  #       limits:
  #         memory: 1024M
  #       reservations:
  #         memory: 200M   

  # user-service:
  #   build:
  #    context: microservices/user-service
  #   depends_on:
  #     - database
  #   networks:
  #     - backend
  #   deploy:
  #     replicas: 1
  #     resources:
  #       limits:
  #         memory: 1024M
  #       reservations:
  #         memory: 200M  
networks:
  backend:
   driver: bridge

volumes:
  pg-data: