basePath: /
host: localhost:80
info:
  contact: {}
  description: This is a sample server celler server.
  title: Swagger of API
  version: "1.0"
paths:
  /ping:
    get:
      description: ping-pong ops...
      responses: {}
swagger: "2.0"
